[package]
name = "vkopt-message-parser"
version = "0.1.0"
authors = ["texbois"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
quick-xml = "0.17"
chrono = "0.4"
clap = "2.33"
