[package]
name = "joebot-message-parser"
version = "0.1.0"
authors = ["texbois"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever = "0.24"
tendril = "0.4"
regex = "1"
lazy_static = "1.4.0"
