[package]
name = "vkopt-message-parser"
version = "0.1.0"
authors = ["texbois"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1.4.0"
quick-xml = "0.17"
chrono = "0.4"

[[example]]
name = "cli"

[dev-dependencies]
clap = "2.33"
